name: Deploy API a producción

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code #clonar el repo y descargarlo en el ubuntu
       uses: actions/checkout@v2
     - name: Setup java
       uses: actions/setup-java@v3 # Usamos la acción para version 17
       with:
         distribution: 'temurin'
         java-version: '17'
     - name: Build with Maven
       run: mvn clean install -DskipTests #compilar el proyecto .jar y desplegar
     - name: Login to DockerHub #conectarse a docker hub
       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
     - name: Build and push Docker image #construir y subir la imagen a docker hub
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dormirios-rest . #nombre de la imagen. el punto es porque se pone en raiz
     - name: Push Docker image #subir la imagen a docker hub
       run: docker push ${{ secrets.DOCKER_USERNAME }}/dormirios-rest